CREATE TABLE `acc_account` (
  `USERID` varchar(50) NOT NULL COMMENT '사용자ID',
  `ACCOUNTID` decimal(10,0) NOT NULL COMMENT '계좌ID',
  `BANKNM` varchar(50) NOT NULL COMMENT '은행명',
  `ACCOUNTNUM` varchar(30) DEFAULT NULL COMMENT '계좌번호',
  `INITMONEY` decimal(10,0) DEFAULT 0 COMMENT '초기잔액',
  `REGID` varchar(50) DEFAULT NULL COMMENT '등록자ID',
  `REGDATE` datetime DEFAULT NULL COMMENT '등록일시',
  `MODID` varchar(50) DEFAULT NULL COMMENT '수정자ID',
  `MODDATE` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`USERID`,`ACCOUNTID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='계좌';

CREATE TABLE `acc_category` (
  `USERID` varchar(50) NOT NULL COMMENT '사용자ID',
  `CATEGORYID` decimal(10,0) NOT NULL COMMENT '항목ID',
  `USAGENM` varchar(100) DEFAULT NULL COMMENT '사용처',
  `CATEGORYNM` varchar(50) NOT NULL COMMENT '항목명',
  `CATEGORYDETAILNM` varchar(100) DEFAULT NULL COMMENT '세부항목명',
  `CLASSIFICATION` varchar(10) NOT NULL COMMENT '분류구분 (INCOME/EXPENSE)',
  `REGID` varchar(50) DEFAULT NULL COMMENT '등록자ID',
  `REGDATE` datetime DEFAULT NULL COMMENT '등록일시',
  `MODID` varchar(50) DEFAULT NULL COMMENT '수정자ID',
  `MODDATE` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`USERID`,`CATEGORYID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='항목';

CREATE TABLE `acc_history` (
  `ACCOUNTID` varchar(50) NOT NULL COMMENT '계좌ID',
  `USERID` varchar(50) NOT NULL COMMENT '사용자ID',
  `TRANID` decimal(10,0) NOT NULL COMMENT '입출금내역ID',
  `TRANTYPE` varchar(10) DEFAULT NULL COMMENT '거래유형 (INCOME/EXPENSE)',
  `TRANAMOUNT` decimal(10,0) DEFAULT NULL COMMENT '거래금액',
  `TRANAFTAMOUNT` decimal(10,0) DEFAULT NULL COMMENT '거래후잔액',
  `DESCRIPTION` varchar(200) DEFAULT NULL COMMENT '적요',
  `CATEGORYID` varchar(50) DEFAULT NULL COMMENT '항목ID',
  `TRANDATE` datetime DEFAULT NULL COMMENT '거래일시',
  `TRANTIME` varchar(8) DEFAULT NULL,
  `DELYN` varchar(1) DEFAULT 'N' COMMENT '삭제여부 (Y/N)',
  `REGID` varchar(50) DEFAULT NULL COMMENT '등록자ID',
  `REGDATE` datetime DEFAULT current_timestamp() COMMENT '등록일시',
  `MODID` varchar(50) DEFAULT NULL COMMENT '수정자ID',
  `MODDATE` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`ACCOUNTID`,`USERID`,`TRANID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='입출금내역';

CREATE TABLE `acc_savings` (
  `SAVINGSID` varchar(50) NOT NULL COMMENT '적금ID',
  `USERID` varchar(50) NOT NULL COMMENT '사용자ID',
  `SAVINGNM` varchar(100) NOT NULL COMMENT '적금명',
  `JOINDATE` datetime NOT NULL COMMENT '가입일',
  `PAYMENTAMOUNT` decimal(10,0) NOT NULL COMMENT '납입금액',
  `INTERESTRATE` decimal(5,2) NOT NULL COMMENT '금리 (예: 2.75)',
  `EXPIRATIONDATE` datetime NOT NULL COMMENT '만기일',
  `STATUS` varchar(10) DEFAULT NULL,
  `BANKNAME` varchar(100) DEFAULT NULL COMMENT '은행명',
  `MEMO` varchar(1000) DEFAULT NULL COMMENT '메모',
  `REGID` varchar(50) DEFAULT NULL COMMENT '등록자ID',
  `REGDATE` datetime DEFAULT NULL COMMENT '등록일시',
  `MODID` varchar(50) DEFAULT NULL COMMENT '수정자ID',
  `MODDATE` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`SAVINGSID`,`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='적금';

CREATE TABLE `acc_savings_history` (
  `HISTORYID` decimal(10,0) NOT NULL COMMENT '납입ID',
  `SAVINGSID` varchar(50) NOT NULL COMMENT '적금ID',
  `USERID` varchar(50) NOT NULL COMMENT '사용자ID',
  `PAYDATE` datetime DEFAULT NULL COMMENT '납입일자',
  `PAYAMOUNT` decimal(10,0) NOT NULL COMMENT '납입금액',
  `TYPE` varchar(10) NOT NULL DEFAULT 'R' COMMENT '정기/추가',
  `IS_PAID` varchar(1) NOT NULL DEFAULT 'N' COMMENT '납입여부',
  `PAYMONTH` varchar(7) DEFAULT NULL COMMENT '납입월(2025-04)',
  `MEMO` varchar(200) DEFAULT NULL COMMENT '메모',
  `REGID` varchar(50) DEFAULT NULL COMMENT '등록자ID',
  `REGDATE` datetime DEFAULT NULL COMMENT '등록일시',
  `MODID` varchar(50) DEFAULT NULL COMMENT '수정자ID',
  `MODDATE` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`HISTORYID`,`SAVINGSID`,`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='납입내역';

CREATE TABLE `acc_user` (
  `USERID` varchar(50) NOT NULL COMMENT '사용자ID',
  `BIRTHDATE` date DEFAULT NULL COMMENT '생년월일',
  `PASSWD` varchar(255) NOT NULL COMMENT '비밀번호',
  `USERNM` varchar(50) NOT NULL COMMENT '사용자명',
  `REGID` varchar(50) DEFAULT NULL COMMENT '등록자ID',
  `REGDATE` datetime DEFAULT NULL COMMENT '등록일시',
  `MODID` varchar(50) DEFAULT NULL COMMENT '수정자ID',
  `MODDATE` datetime DEFAULT NULL COMMENT '수정일시',
  `PHONENUM` varchar(13) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자목록';